### ISSUE TITLE
Basic setup provided in Getting Started Is not working

### ISSUE THREAD

**Issue by ghana7989** [guidone/lets-form#18] opened 2024-04-17 07:41 UTC
I am using vite to create the app but I am getting this error.
any guidelines on how to setup it in vite
> Uncaught TypeError: Cannot read properties of undefined (reading 'webpackChunklets_form_react')
    at jsonp chunk loading:86:98
    at jsonp chunk loading:88:88
    at startup:4:47
    at universalModuleDefinition:3:20
    at node_modules/lets-form/dist/react/main.js (universalModuleDefinition:10:2)
    at __require (chunk-4YP5LC2O.js?v=a0a6cf6f:3:50)
    at startup:4:47

**Comment by guidone** [comment] 2024-04-17 07:47
Hi, never tried with Vite but it's planned.
The idea is to add an export button for Vite here

<img width="1512" alt="image" src="https://github.com/guidone/lets-form/assets/502519/3d5ccea8-d1b3-4099-96e2-272a509b0e3f">

The problem is it's with the chunks, for some reason is not able to load them, I'll give a look.
(Do you see something in the dev tool network panel?)

Thanks for the feedback

**Comment by ghana7989** [comment] 2024-04-17 08:33
if you have references or things to look at please share with me I will also have a look, might be helpful for us

**Comment by ghana7989** [comment] 2024-04-17 08:38
Hi @guidone,
Also, adding that button to export to vite would be great, but I think a better solution would be to have documentation for vite setup. Because I am planning to create a good number of forms it is ideal that I copy the schema paste in my local JSON and import it to use it.

**Comment by guidone** [comment] 2024-04-17 08:42
Ok, perhaps what you need is this

https://letsform.dev/lets-form-designer/export-to-github

It's basically exporting all JSON forms to a GitHub project/folder with few clicks, LetsForm has a lot of forms too and I use this feature for LetsForm designer.

It's a paid feature but I would be happy to offer a free subscription for you for for testing

**Comment by guidone** [comment] 2024-04-23 20:29
Fixed in LetsForm Designer `0.8.5`

**Closed by guidone** 2024-04-23 20:29 UTC
Labels: bug
